package imageutil

import (
	"context"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/1broseidon/mc/internal/contract"
)

// loadFixturePNG reads a PNG from testdata into an *image.RGBA.
func loadFixturePNG(t *testing.T, name string) *image.RGBA {
	t.Helper()
	f, err := os.Open(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("open fixture %s: %v", name, err)
	}
	defer func() { _ = f.Close() }()
	src, err := png.Decode(f)
	if err != nil {
		t.Fatalf("decode fixture %s: %v", name, err)
	}
	b := src.Bounds()
	dst := image.NewRGBA(image.Rect(0, 0, b.Dx(), b.Dy()))
	draw.Draw(dst, dst.Bounds(), src, b.Min, draw.Src)
	return dst
}

func tesseractAvailable() bool {
	_, err := exec.LookPath("tesseract")
	return err == nil
}

func TestFindText_HappyPath(t *testing.T) {
	if !tesseractAvailable() {
		t.Skip("tesseract not on PATH")
	}
	img := loadFixturePNG(t, "hello_world.png")
	region := contract.Bounds{X: 0, Y: 0, Width: img.Bounds().Dx(), Height: img.Bounds().Dy()}
	res, err := FindText(context.Background(), nil, region, img, FindTextRequest{Query: "hello"})
	if err != nil {
		t.Fatalf("FindText error: %v", err)
	}
	if len(res.Candidates) == 0 {
		t.Fatalf("expected at least one candidate for 'hello', got 0")
	}
	if res.CoordSpace != contract.CoordSpaceScreen {
		t.Errorf("CoordSpace = %q, want %q", res.CoordSpace, contract.CoordSpaceScreen)
	}
	if res.Candidates[0].Source != contract.FindSourceOCR {
		t.Errorf("source = %q, want ocr", res.Candidates[0].Source)
	}
	// Bounds should sit inside the search region.
	c := res.Candidates[0]
	if !region.Contains(c.Bounds.X, c.Bounds.Y) {
		t.Errorf("candidate %+v outside region %+v", c.Bounds, region)
	}
	if c.Confidence <= 0 {
		t.Errorf("confidence should be > 0, got %v", c.Confidence)
	}
}

func TestFindText_NoMatchReturnsEmpty(t *testing.T) {
	if !tesseractAvailable() {
		t.Skip("tesseract not on PATH")
	}
	img := loadFixturePNG(t, "hello_world.png")
	region := contract.Bounds{X: 0, Y: 0, Width: img.Bounds().Dx(), Height: img.Bounds().Dy()}
	res, err := FindText(context.Background(), nil, region, img, FindTextRequest{Query: "xyzzy"})
	if err != nil {
		t.Fatalf("FindText error: %v", err)
	}
	if len(res.Candidates) != 0 {
		t.Fatalf("expected 0 candidates for missing query, got %d", len(res.Candidates))
	}
}

func TestFindText_RegexAndCase(t *testing.T) {
	if !tesseractAvailable() {
		t.Skip("tesseract not on PATH")
	}
	img := loadFixturePNG(t, "hello_world.png")
	region := contract.Bounds{X: 0, Y: 0, Width: img.Bounds().Dx(), Height: img.Bounds().Dy()}
	res, err := FindText(context.Background(), nil, region, img, FindTextRequest{Query: `^h.llo$`, Regex: true})
	if err != nil {
		t.Fatalf("FindText regex error: %v", err)
	}
	if len(res.Candidates) == 0 {
		t.Fatalf("expected regex match for ^h.llo$")
	}
	res, err = FindText(context.Background(), nil, region, img, FindTextRequest{Query: "HELLO", CaseSensitive: true})
	if err != nil {
		t.Fatalf("FindText case error: %v", err)
	}
	if len(res.Candidates) != 0 {
		t.Errorf("case-sensitive search for HELLO should miss lower-case fixture, got %d", len(res.Candidates))
	}
}

func TestFindText_BatchCacheReusesOCR(t *testing.T) {
	if !tesseractAvailable() {
		t.Skip("tesseract not on PATH")
	}
	img := loadFixturePNG(t, "hello_world.png")
	region := contract.Bounds{X: 0, Y: 0, Width: img.Bounds().Dx(), Height: img.Bounds().Dy()}
	bctx := NewBatchContext()
	if _, err := FindText(context.Background(), bctx, region, img, FindTextRequest{Query: "hello"}); err != nil {
		t.Fatalf("first call: %v", err)
	}
	first := bctx.OCRCalls()
	if _, err := FindText(context.Background(), bctx, region, img, FindTextRequest{Query: "world"}); err != nil {
		t.Fatalf("second call: %v", err)
	}
	second := bctx.OCRCalls()
	if first != 1 || second != 1 {
		t.Fatalf("OCR was invoked %d then %d times, want 1 then 1 (batch cache hit)", first, second)
	}
}

// TestFindTextDarkTheme is the headline task-8 fixture test. It
// verifies the auto-invert pipeline activates on a synthetic dark-mode
// calculator readout ("40" in white on #1f1f1f) — the same shape as
// the failing v0.2 gnome-calculator smoke.
//
// Fixtures are generated by a tiny helper program kept in this repo
// alongside this test (see comment at the top of
// internal/image/testdata for regeneration instructions). They are
// hand-crafted bitmap glyphs (5x7 at scale 5 == 35px tall) — no
// external Go dependencies.
func TestFindTextDarkTheme(t *testing.T) {
	if !tesseractAvailable() {
		t.Skip("tesseract not on PATH")
	}
	dark := loadFixturePNG(t, "dark_calc_display.png")
	light := loadFixturePNG(t, "light_calc_display.png")
	darkRegion := contract.Bounds{X: 0, Y: 0, Width: dark.Bounds().Dx(), Height: dark.Bounds().Dy()}
	lightRegion := contract.Bounds{X: 0, Y: 0, Width: light.Bounds().Dx(), Height: light.Bounds().Dy()}

	// (a) auto on dark fixture → at least one candidate, applied=invert.
	res, err := FindText(context.Background(), nil, darkRegion, dark, FindTextRequest{Query: "40", Preprocess: "auto"})
	if err != nil {
		t.Fatalf("auto FindText (dark) error: %v", err)
	}
	if len(res.Candidates) == 0 {
		t.Fatalf("auto on dark fixture: expected >=1 candidate, got 0")
	}
	if got, _ := res.Candidates[0].Extra["preprocess"].(string); got != "invert" {
		t.Errorf("auto on dark fixture: applied=%q, want %q", got, "invert")
	}
	if c := res.Candidates[0].Confidence; c <= 0.5 {
		t.Errorf("auto on dark fixture: top confidence %.3f, want > 0.5", c)
	}

	// (b) auto on light fixture → applied=none (luminance above threshold).
	res2, err := FindText(context.Background(), nil, lightRegion, light, FindTextRequest{Query: "40", Preprocess: "auto"})
	if err != nil {
		t.Fatalf("auto FindText (light) error: %v", err)
	}
	if len(res2.Candidates) == 0 {
		t.Fatalf("auto on light fixture: expected >=1 candidate, got 0")
	}
	if got, _ := res2.Candidates[0].Extra["preprocess"].(string); got != "none" {
		t.Errorf("auto on light fixture: applied=%q, want %q (no inversion on light bg)", got, "none")
	}

	// (c) preprocess=none on dark fixture → applied=none (opt-out works).
	res3, err := FindText(context.Background(), nil, darkRegion, dark, FindTextRequest{Query: "40", Preprocess: "none"})
	if err != nil {
		t.Fatalf("none FindText (dark) error: %v", err)
	}
	for _, c := range res3.Candidates {
		if got, _ := c.Extra["preprocess"].(string); got != "none" {
			t.Errorf("preprocess=none on dark fixture: applied=%q, want %q (must not auto-invert)", got, "none")
		}
	}

	// (d) preprocess=invert on light fixture → applied=invert
	// (proves explicit-invert path is honored regardless of luminance).
	res4, err := FindText(context.Background(), nil, lightRegion, light, FindTextRequest{Query: "40", Preprocess: "invert"})
	if err != nil {
		t.Fatalf("invert FindText (light) error: %v", err)
	}
	if len(res4.Candidates) == 0 {
		t.Fatalf("explicit invert on light fixture: expected >=1 candidate, got 0")
	}
	if got, _ := res4.Candidates[0].Extra["preprocess"].(string); got != "invert" {
		t.Errorf("explicit invert on light fixture: applied=%q, want %q", got, "invert")
	}
}

// TestPreprocessImage_AutoDetectsDark unit-tests the luminance scanner
// without invoking tesseract. Synthesized 32x32 buffers: one all-dark,
// one all-light, one mixed at the threshold.
func TestPreprocessImage_AutoDetectsDark(t *testing.T) {
	mk := func(r, g, b uint8) *image.RGBA {
		im := image.NewRGBA(image.Rect(0, 0, 32, 32))
		for y := 0; y < 32; y++ {
			for x := 0; x < 32; x++ {
				im.SetRGBA(x, y, color.RGBA{r, g, b, 255})
			}
		}
		return im
	}
	cases := []struct {
		name    string
		img     *image.RGBA
		want    string
		wantInv bool // expect pixel inversion to have occurred
	}{
		{"all-dark", mk(0x1f, 0x1f, 0x1f), "invert", true},
		{"all-light", mk(0xff, 0xff, 0xff), "none", false},
		{"medium-gray-above-threshold", mk(120, 120, 120), "none", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			out, applied := preprocessImage(tc.img, "auto")
			if applied != tc.want {
				t.Errorf("applied=%q, want %q", applied, tc.want)
			}
			top := out.RGBAAt(0, 0)
			src := tc.img.RGBAAt(0, 0)
			inverted := top.R != src.R || top.G != src.G || top.B != src.B
			if inverted != tc.wantInv {
				t.Errorf("inversion happened=%v, want %v", inverted, tc.wantInv)
			}
		})
	}
}

// TestPreprocessImage_ExplicitModes covers invert/binarize/none modes
// without tesseract.
func TestPreprocessImage_ExplicitModes(t *testing.T) {
	img := image.NewRGBA(image.Rect(0, 0, 4, 4))
	for y := 0; y < 4; y++ {
		for x := 0; x < 4; x++ {
			img.SetRGBA(x, y, color.RGBA{50, 100, 200, 255})
		}
	}
	inv, applied := preprocessImage(img, "invert")
	if applied != "invert" {
		t.Errorf("applied=%q, want invert", applied)
	}
	if got := inv.RGBAAt(0, 0); got.R != 205 || got.G != 155 || got.B != 55 || got.A != 255 {
		t.Errorf("invert pixel = %+v, want {205,155,55,255}", got)
	}
	none, applied := preprocessImage(img, "none")
	if applied != "none" || none.RGBAAt(0, 0) != img.RGBAAt(0, 0) {
		t.Errorf("none mode mutated pixels or label (applied=%q)", applied)
	}
	// Binarize a half-dark / half-light buffer: Otsu should split cleanly.
	bin := image.NewRGBA(image.Rect(0, 0, 4, 4))
	for y := 0; y < 4; y++ {
		for x := 0; x < 4; x++ {
			if x < 2 {
				bin.SetRGBA(x, y, color.RGBA{0, 0, 0, 255})
			} else {
				bin.SetRGBA(x, y, color.RGBA{255, 255, 255, 255})
			}
		}
	}
	bout, applied := preprocessImage(bin, "binarize")
	if applied != "binarize" {
		t.Errorf("applied=%q, want binarize", applied)
	}
	if got := bout.RGBAAt(0, 0); got.R != 0 {
		t.Errorf("dark pixel after binarize: R=%d, want 0", got.R)
	}
	if got := bout.RGBAAt(3, 0); got.R != 255 {
		t.Errorf("light pixel after binarize: R=%d, want 255", got.R)
	}
}

// TestFindText_CacheKeyIncludesPreprocess verifies the batch cache does
// not false-hit across different preprocess modes (constraint: different
// OCR settings must not collide).
func TestFindText_CacheKeyIncludesPreprocess(t *testing.T) {
	if !tesseractAvailable() {
		t.Skip("tesseract not on PATH")
	}
	img := loadFixturePNG(t, "dark_calc_display.png")
	region := contract.Bounds{X: 0, Y: 0, Width: img.Bounds().Dx(), Height: img.Bounds().Dy()}
	bctx := NewBatchContext()
	if _, err := FindText(context.Background(), bctx, region, img, FindTextRequest{Query: "40", Preprocess: "auto"}); err != nil {
		t.Fatalf("auto call: %v", err)
	}
	if got := bctx.OCRCalls(); got != 1 {
		t.Fatalf("after auto call OCRCalls=%d, want 1", got)
	}
	if _, err := FindText(context.Background(), bctx, region, img, FindTextRequest{Query: "40", Preprocess: "none"}); err != nil {
		t.Fatalf("none call: %v", err)
	}
	if got := bctx.OCRCalls(); got != 2 {
		t.Fatalf("after none call OCRCalls=%d, want 2 (different preprocess must miss cache)", got)
	}
}

// TestFindText_MultiWordPhrase covers v0.3 epic-2 task-15: matching a
// multi-word query against the joined text of consecutive OCR tokens.
// Single-token literal queries must still produce byte-identical
// candidate streams (backward-compat constraint), so the regression
// guard is the same fixture & query as TestFindText_HappyPath.
func TestFindText_MultiWordPhrase(t *testing.T) {
	// (a) Two-word query against the hello_world fixture: tokens are
	//     "hello" and "world"; "hello world" must hit as a phrase
	//     candidate whose bounds span both tokens.
	if tesseractAvailable() {
		img := loadFixturePNG(t, "hello_world.png")
		region := contract.Bounds{X: 0, Y: 0, Width: img.Bounds().Dx(), Height: img.Bounds().Dy()}
		res, err := FindText(context.Background(), nil, region, img, FindTextRequest{Query: "hello world"})
		if err != nil {
			t.Fatalf("two-word FindText error: %v", err)
		}
		if len(res.Candidates) == 0 {
			t.Fatalf("expected >=1 candidate for 'hello world', got 0")
		}
		// Top candidate should be the phrase: token count >= 2 and
		// bounds wider than either single token.
		top := res.Candidates[0]
		if tc, _ := top.Extra["tokens"].(int); tc < 2 {
			t.Errorf("top candidate tokens=%v, want >=2 (phrase match)", top.Extra["tokens"])
		}
		gotText, _ := top.Extra["text"].(string)
		// Phrase text is "hello world" (case-insensitive substring
		// match is the default, so casing depends on what tesseract
		// emitted — assert via lowercase contains).
		if !strings.Contains(strings.ToLower(gotText), "hello world") {
			t.Errorf("top candidate text=%q, want it to contain 'hello world'", gotText)
		}
		// Width must span more than a single token (~94px) — both
		// tokens together are ~191px wide in the fixture.
		if top.Bounds.Width < 150 {
			t.Errorf("phrase bounds too narrow: width=%d, want >=150 (spanning both tokens)", top.Bounds.Width)
		}

		// (c) Regression: single-word query produces the same shape as
		//     the v0.2 baseline (TestFindText_HappyPath asserts the
		//     same invariants). Re-running here ensures phrase mode
		//     stayed off and no duplicate candidates were emitted.
		resSingle, err := FindText(context.Background(), nil, region, img, FindTextRequest{Query: "hello"})
		if err != nil {
			t.Fatalf("single-word FindText error: %v", err)
		}
		// Should be exactly one candidate for "hello" — the token
		// match. No phrase candidate (multiwordMode is gated on
		// whitespace in query).
		if len(resSingle.Candidates) != 1 {
			t.Errorf("single-word 'hello': got %d candidates, want 1 (no phrase duplication)", len(resSingle.Candidates))
		}
		if len(resSingle.Candidates) > 0 {
			if _, hasTokens := resSingle.Candidates[0].Extra["tokens"]; hasTokens {
				t.Errorf("single-word candidate should not carry 'tokens' extra: %+v", resSingle.Candidates[0].Extra)
			}
		}
	}

	// (b) Three-word phrase via synthetic OCR tokens — exercises
	//     phraseMatchUnits independent of tesseract. Tokens lie on the
	//     same (block, par, line) so the joiner reaches len=3.
	words := []ocrWord{
		{text: "Loaded", left: 10, top: 5, width: 50, height: 14, confidence: 0.95, block: 1, par: 1, line: 1},
		{text: "skill", left: 65, top: 5, width: 40, height: 14, confidence: 0.93, block: 1, par: 1, line: 1},
		{text: "anvil", left: 110, top: 5, width: 45, height: 14, confidence: 0.91, block: 1, par: 1, line: 1},
		// Next line, must NOT be joined into the above phrase.
		{text: "Other", left: 10, top: 25, width: 50, height: 14, confidence: 0.9, block: 1, par: 1, line: 2},
	}
	phrases := phraseMatchUnits(words, maxPhraseTokens)
	var got3 *matchUnit
	for i := range phrases {
		if phrases[i].text == "Loaded skill anvil" {
			got3 = &phrases[i]
			break
		}
	}
	if got3 == nil {
		var texts []string
		for _, p := range phrases {
			texts = append(texts, p.text)
		}
		t.Fatalf("three-word phrase 'Loaded skill anvil' not generated; got phrases: %v", texts)
	}
	if got3.tokenCount != 3 {
		t.Errorf("three-word phrase tokenCount=%d, want 3", got3.tokenCount)
	}
	// Bounds union: left=10, top=5, right=155 (110+45), bottom=19 (5+14).
	if got3.left != 10 || got3.top != 5 || got3.width != 145 || got3.height != 14 {
		t.Errorf("phrase bounds = (%d,%d,%dx%d), want (10,5,145x14)", got3.left, got3.top, got3.width, got3.height)
	}
	// Confidence = min(0.95, 0.93, 0.91) = 0.91.
	if got3.confidence < 0.909 || got3.confidence > 0.911 {
		t.Errorf("phrase confidence=%v, want ~0.91 (min of constituents)", got3.confidence)
	}
	// Line-boundary respect: no phrase should contain "Other".
	for _, p := range phrases {
		if strings.Contains(p.text, "Other") {
			t.Errorf("phrase %q crosses line boundary into next-line token", p.text)
		}
	}

	// (d) Regex with `\s` whitespace pattern must match across tokens.
	//     Build a tiny image-free path by exercising the matcher logic
	//     via FindText with synthetic words is awkward; instead we
	//     verify the regex matches the phrase text generated above.
	re := regexp.MustCompile(`(?i)Loaded\s+skill`)
	if !re.MatchString(got3.text) {
		t.Errorf("regex 'Loaded\\s+skill' did not match phrase text %q", got3.text)
	}
	// Also confirm the regex would not match against token-only text
	// (the bug pre-task-15): no single token contains "Loaded skill".
	for _, w := range words {
		if re.MatchString(w.text) {
			t.Errorf("token %q unexpectedly matched 'Loaded\\s+skill' (token-only regex should miss)", w.text)
		}
	}
}

// TestFindText_SmartPSMRetry exercises the v0.3.1 auto-retry path
// (task-30). Strategy: seed the batch OCR cache so runOCR returns
// synthetic ocrWords without invoking tesseract. We pin two cache
// entries against the same prepped image — psm=0 returns no words,
// psm=11 returns the target token — and assert FindText surfaces
// psm_retried=true / psm_used=11 on the resulting candidate.
//
// Why bypass tesseract: real Tesseract output for a given fixture is
// not stable enough across tesseract versions to guarantee
// "default PSM misses, psm=11 hits"; the cache-seed approach pins the
// exact behavior the retry path must handle.
func TestFindText_SmartPSMRetry(t *testing.T) {
	if !tesseractAvailable() {
		// runOCR still LookPath()s tesseract before consulting cache.
		t.Skip("tesseract not on PATH")
	}
	// Small region (200*60 = 12_000 px², well below the 100_000 px²
	// gate). Pixels are all white so preprocessImage("auto") returns
	// applied="none" and `prepped` is the same buffer — making the
	// cache hash deterministic from the input image alone.
	region := contract.Bounds{X: 50, Y: 100, Width: 200, Height: 60}
	img := image.NewRGBA(image.Rect(0, 0, 200, 60))
	for y := 0; y < 60; y++ {
		for x := 0; x < 200; x++ {
			img.SetRGBA(x, y, color.RGBA{255, 255, 255, 255})
		}
	}
	bctx := NewBatchContext()
	hash := hashImage(region, img)
	// psm=0 → no words (forces the gate to fire).
	bctx.ocr["eng|none|"+hash+"|psm=0|oem=0"] = ocrEntry{words: nil}
	// psm=11 → one synthetic word matching the query "OK".
	bctx.ocr["eng|none|"+hash+"|psm=11|oem=0"] = ocrEntry{words: []ocrWord{
		{text: "OK", left: 20, top: 10, width: 40, height: 30, confidence: 0.92, block: 1, par: 1, line: 1},
	}}

	res, err := FindText(context.Background(), bctx, region, img, FindTextRequest{Query: "OK"})
	if err != nil {
		t.Fatalf("FindText error: %v", err)
	}
	if len(res.Candidates) != 1 {
		t.Fatalf("got %d candidates, want 1 (auto-retry should surface psm=11 result)", len(res.Candidates))
	}
	got := res.Candidates[0]
	if retried, _ := got.Extra["psm_retried"].(bool); !retried {
		t.Errorf("psm_retried = %v, want true (extra=%v)", got.Extra["psm_retried"], got.Extra)
	}
	if used, _ := got.Extra["psm_used"].(int); used != 11 {
		t.Errorf("psm_used = %v, want 11 (extra=%v)", got.Extra["psm_used"], got.Extra)
	}
	// Bounds must be region-relative-shifted into screen space.
	if got.Bounds.X != region.X+20 || got.Bounds.Y != region.Y+10 {
		t.Errorf("bounds = %+v, want region+local offset (X=%d, Y=%d)", got.Bounds, region.X+20, region.Y+10)
	}
}

// TestFindText_SmartPSMRetry_GateNegatives covers the cases where the
// auto-retry MUST NOT fire: explicit psm, and large region. We assert
// the retry didn't happen by checking that no second cache entry was
// touched and that no psm_retried marker appears on any candidate.
func TestFindText_SmartPSMRetry_GateNegatives(t *testing.T) {
	if !tesseractAvailable() {
		t.Skip("tesseract not on PATH")
	}

	// Case A: caller passes explicit psm — retry disabled by contract.
	t.Run("explicit_psm_disables_retry", func(t *testing.T) {
		region := contract.Bounds{X: 0, Y: 0, Width: 200, Height: 60}
		img := image.NewRGBA(image.Rect(0, 0, 200, 60))
		for y := 0; y < 60; y++ {
			for x := 0; x < 200; x++ {
				img.SetRGBA(x, y, color.RGBA{255, 255, 255, 255})
			}
		}
		bctx := NewBatchContext()
		hash := hashImage(region, img)
		// Caller asked for psm=6 explicitly. Seed only that cache key
		// with no words. Seeing the retry would require a psm=11 entry
		// which is intentionally absent — if the retry fires it would
		// shell out to tesseract (and the result would still be empty
		// on this blank fixture, but we'd see OCRCalls increment).
		bctx.ocr["eng|none|"+hash+"|psm=6|oem=0"] = ocrEntry{words: nil}
		callsBefore := bctx.OCRCalls()
		res, err := FindText(context.Background(), bctx, region, img, FindTextRequest{Query: "OK", PSM: 6})
		if err != nil {
			t.Fatalf("FindText error: %v", err)
		}
		if len(res.Candidates) != 0 {
			t.Errorf("expected 0 candidates on blank fixture, got %d", len(res.Candidates))
		}
		// No tesseract invocation should have happened (cache hit on
		// the psm=6 entry, no retry).
		if got := bctx.OCRCalls() - callsBefore; got != 0 {
			t.Errorf("OCRCalls delta = %d, want 0 (explicit psm must not trigger retry)", got)
		}
	})

	// Case B: large region — area >= smartPSMRegionThresholdPx, so
	// retry is gated off even when the first pass returns nothing.
	t.Run("large_region_disables_retry", func(t *testing.T) {
		// 400x300 = 120_000 px² > 100_000 threshold.
		region := contract.Bounds{X: 0, Y: 0, Width: 400, Height: 300}
		img := image.NewRGBA(image.Rect(0, 0, 400, 300))
		for y := 0; y < 300; y++ {
			for x := 0; x < 400; x++ {
				img.SetRGBA(x, y, color.RGBA{255, 255, 255, 255})
			}
		}
		bctx := NewBatchContext()
		hash := hashImage(region, img)
		bctx.ocr["eng|none|"+hash+"|psm=0|oem=0"] = ocrEntry{words: nil}
		callsBefore := bctx.OCRCalls()
		res, err := FindText(context.Background(), bctx, region, img, FindTextRequest{Query: "OK"})
		if err != nil {
			t.Fatalf("FindText error: %v", err)
		}
		if len(res.Candidates) != 0 {
			t.Errorf("expected 0 candidates on blank large fixture, got %d", len(res.Candidates))
		}
		if got := bctx.OCRCalls() - callsBefore; got != 0 {
			t.Errorf("OCRCalls delta = %d, want 0 (large region must not trigger retry)", got)
		}
	})
}

func TestFindImage_FindsTemplate(t *testing.T) {
	haystack := loadFixturePNG(t, "hello_world.png")
	region := contract.Bounds{X: 0, Y: 0, Width: haystack.Bounds().Dx(), Height: haystack.Bounds().Dy()}
	tmplPath := filepath.Join("testdata", "hello_template.png")
	res, err := FindImage(context.Background(), region, haystack, FindImageRequest{
		TemplatePath: tmplPath,
		Threshold:    0.85,
	})
	if err != nil {
		t.Fatalf("FindImage error: %v", err)
	}
	if len(res.Candidates) == 0 {
		t.Fatalf("expected at least one template hit")
	}
	if res.Candidates[0].Source != contract.FindSourceTemplate {
		t.Errorf("source = %q, want template", res.Candidates[0].Source)
	}
	if res.Candidates[0].Confidence < 0.85 {
		t.Errorf("top confidence %v below threshold 0.85", res.Candidates[0].Confidence)
	}
}

func TestFindImage_TemplateNotFound(t *testing.T) {
	haystack := loadFixturePNG(t, "hello_world.png")
	region := contract.Bounds{X: 0, Y: 0, Width: haystack.Bounds().Dx(), Height: haystack.Bounds().Dy()}
	_, err := FindImage(context.Background(), region, haystack, FindImageRequest{TemplatePath: "testdata/missing.png"})
	if err == nil {
		t.Fatalf("expected NotFound error for missing template")
	}
	if !strings.Contains(err.Error(), "could not be opened") {
		t.Errorf("error message = %q, want open-failure prose", err.Error())
	}
}

func TestFindColor_PointSample(t *testing.T) {
	// Build a 2x2 image with one red pixel at (1,1).
	img := image.NewRGBA(image.Rect(0, 0, 2, 2))
	draw.Draw(img, img.Bounds(), &image.Uniform{C: color.RGBA{255, 255, 255, 255}}, image.Point{}, draw.Src)
	img.SetRGBA(1, 1, color.RGBA{255, 0, 0, 255})
	region := contract.Bounds{X: 100, Y: 200, Width: 2, Height: 2}
	res, err := FindColor(context.Background(), region, img, FindColorRequest{
		Point: &contract.Point{X: 101, Y: 201, Space: contract.CoordSpaceScreen},
	})
	if err != nil {
		t.Fatalf("FindColor point error: %v", err)
	}
	if len(res.Candidates) != 1 {
		t.Fatalf("expected 1 candidate, got %d", len(res.Candidates))
	}
	hex, _ := res.Candidates[0].Extra["hex"].(string)
	if hex != "#ff0000" {
		t.Errorf("hex = %q, want #ff0000", hex)
	}
}

func TestFindColor_BlobDetection(t *testing.T) {
	// 10x10 with a 3x3 red blob at (2,2)-(4,4).
	img := image.NewRGBA(image.Rect(0, 0, 10, 10))
	draw.Draw(img, img.Bounds(), &image.Uniform{C: color.RGBA{255, 255, 255, 255}}, image.Point{}, draw.Src)
	for y := 2; y <= 4; y++ {
		for x := 2; x <= 4; x++ {
			img.SetRGBA(x, y, color.RGBA{255, 0, 0, 255})
		}
	}
	region := contract.Bounds{X: 0, Y: 0, Width: 10, Height: 10}
	res, err := FindColor(context.Background(), region, img, FindColorRequest{
		Color: "#ff0000",
	})
	if err != nil {
		t.Fatalf("FindColor blob error: %v", err)
	}
	if len(res.Candidates) != 1 {
		t.Fatalf("expected exactly 1 blob, got %d", len(res.Candidates))
	}
	got := res.Candidates[0].Bounds
	want := contract.Bounds{X: 2, Y: 2, Width: 3, Height: 3}
	if got != want {
		t.Errorf("blob bounds = %+v, want %+v", got, want)
	}
}

func TestFindColor_PointOutOfBounds(t *testing.T) {
	img := image.NewRGBA(image.Rect(0, 0, 4, 4))
	region := contract.Bounds{X: 0, Y: 0, Width: 4, Height: 4}
	_, err := FindColor(context.Background(), region, img, FindColorRequest{
		Point: &contract.Point{X: 999, Y: 999, Space: contract.CoordSpaceScreen},
	})
	if err == nil {
		t.Fatalf("expected out-of-bounds error")
	}
}

func TestSortCandidates_Order(t *testing.T) {
	cands := []contract.FindCandidate{
		{Bounds: contract.Bounds{X: 10, Y: 100}, Confidence: 0.9},
		{Bounds: contract.Bounds{X: 0, Y: 100}, Confidence: 0.9},
		{Bounds: contract.Bounds{X: 0, Y: 50}, Confidence: 0.9},
		{Bounds: contract.Bounds{X: 0, Y: 0}, Confidence: 0.95},
	}
	sortCandidates(cands)
	if cands[0].Confidence != 0.95 {
		t.Errorf("first should be top confidence, got %v", cands[0].Confidence)
	}
	if cands[1].Bounds.Y != 50 {
		t.Errorf("second should be y=50, got %+v", cands[1].Bounds)
	}
	if cands[2].Bounds.X != 0 || cands[3].Bounds.X != 10 {
		t.Errorf("tie-broken order wrong: %+v %+v", cands[2].Bounds, cands[3].Bounds)
	}
}

func TestProbeOCRTesseract_ReportsBinary(t *testing.T) {
	status := ProbeOCRTesseract()
	if status.Name != "ocr_tesseract" {
		t.Errorf("name = %q, want ocr_tesseract", status.Name)
	}
	if status.Required {
		t.Errorf("ocr_tesseract should be optional")
	}
	if tesseractAvailable() {
		if !status.Ready {
			t.Errorf("tesseract is on PATH but status reports not ready: %s", status.Message)
		}
		if psm, _ := status.Details["supported_psm"].(string); psm != "0..13" {
			t.Errorf("supported_psm = %q, want 0..13", psm)
		}
		if oem, _ := status.Details["supported_oem"].(string); oem != "0..3" {
			t.Errorf("supported_oem = %q, want 0..3", oem)
		}
		if v, _ := status.Details["version"].(string); v == "" {
			t.Errorf("expected non-empty version detail, got empty")
		}
	}
}

func TestProbeTemplateMatch_ReportsBackend(t *testing.T) {
	status := ProbeTemplateMatch()
	if status.Name != "template_match" {
		t.Errorf("name = %q, want template_match", status.Name)
	}
	if !status.Ready {
		t.Errorf("template_match should always be ready (pure_go or opencv)")
	}
}
