package pipeline

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/1broseidon/mc/internal/a11y"
	"github.com/1broseidon/mc/internal/audit"
	"github.com/1broseidon/mc/internal/clipboard"
	"github.com/1broseidon/mc/internal/contract"
	imageutil "github.com/1broseidon/mc/internal/image"
	"github.com/1broseidon/mc/internal/input"
	"github.com/1broseidon/mc/internal/platform"
	"github.com/1broseidon/mc/internal/screen"
	"github.com/1broseidon/mc/internal/wait"
	"github.com/1broseidon/mc/internal/window"
)

// dryRunTypeTextRoute computes the (via, reason) the live type_text
// action would have used, without performing any XTest or paste side
// effect. It mirrors TypeTextWith's branching:
//
//   - explicit via:"xtest" → returns ("xtest", "explicit") or
//     ("paste","ime-active-blocked") if an IME is active (the live
//     path would have errored with INPUT_IME_ACTIVE; the preview
//     surfaces what the route WOULD have been and why it would have
//     failed).
//   - explicit via:"paste" → returns ("paste", "explicit").
//   - via:"" or "auto"     → delegates to input.DecideTypeTextRoute.
//
// The reason tag set is the union of input.DecideTypeTextRoute's tags
// plus the dry-run-only "explicit" and "ime-active-blocked" tags. The
// dry-run-only tags never appear in the live ActionResult path —
// callers can rely on them to distinguish "auto picked this" from
// "the caller forced this".
func dryRunTypeTextRoute(text, viaIn string) (via, reason string) {
	ime := clipboard.DetectIME()
	switch viaIn {
	case input.TypeTextViaXTest:
		if ime.Active {
			return input.TypeTextViaXTest, "ime-active-blocked"
		}
		return input.TypeTextViaXTest, "explicit"
	case input.TypeTextViaPaste:
		return input.TypeTextViaPaste, "explicit"
	}
	return input.DecideTypeTextRoute(text, ime.Active)
}

// pointResolveCandidates returns the slice of Points that participate
// in coordinate resolution for the given action. Used by the dry-run
// preview to hydrate a ResolveContext that covers every relevant space
// (window / window_frame / monitor) before calling contract.Resolve.
// Empty / zero-value points are filtered out by callers.
func pointResolveCandidates(a Action) []contract.Point {
	pts := make([]contract.Point, 0, 3)
	if !pointZero(a.Point) {
		pts = append(pts, a.Point)
	}
	if !pointZero(a.From) {
		pts = append(pts, a.From)
	}
	if !pointZero(a.To) {
		pts = append(pts, a.To)
	}
	return pts
}

// DefaultQuietMS is the default "user has gone quiet" window after a
// yield observation. Controls how quickly MC resumes once the human
// stops driving the desktop. Overridable per batch and per CLI flag.
const DefaultQuietMS = 1500

// DefaultYieldTimeoutMS is the default upper bound on how long the
// pipeline will wait for the user to go quiet before aborting the
// batch with contract.Cancelled / code YIELDED_TO_USER.
const DefaultYieldTimeoutMS = 30000

// auditWriter is the package-level audit Writer used by Run. Exposed
// so tests (and the CLI replay subcommand) can swap in a tempdir-
// rooted writer without touching the global state. Defaults to a
// lazily-initialized Writer rooted at audit.DefaultDir().
var auditWriter = audit.New()

// SetAuditWriter replaces the package-level audit writer. Intended
// for tests; production code should leave the default in place.
func SetAuditWriter(w *audit.Writer) { auditWriter = w }

// AuditWriter returns the active audit writer.
func AuditWriter() *audit.Writer { return auditWriter }

type ActionBatch struct {
	// SchemaVersion is the action-payload schema version. Required.
	// A missing or empty value is rejected with
	// VALIDATION_SCHEMA_VERSION_REQUIRED. An unsupported value is
	// rejected with VALIDATION_SCHEMA_VERSION_UNSUPPORTED. See
	// contract.SupportedSchemaVersions for the accepted set.
	// NOTE: this field uses omitempty so JSON-schema validation in the
	// MCP SDK does not pre-reject the payload with a generic missing-
	// property error. The canonical missing-field error is generated by
	// contract.ValidateSchemaVersion below, with code
	// VALIDATION_SCHEMA_VERSION_REQUIRED and a remediation hint.
	SchemaVersion string   `json:"schema_version,omitempty" jsonschema:"required action-payload schema version; must equal \"0.2\""`
	Actions       []Action `json:"actions"`
	// AllowClose, when true, permits window_close actions inside this
	// batch. Defaults false. The CLI also exposes a --allow-close flag
	// that flips this on for command-line driven batches; either source
	// is sufficient. window_close without allow_close=true returns
	// PRECONDITION_CLOSE_NOT_ALLOWED.
	AllowClose bool `json:"allow_close,omitempty" jsonschema:"permit window_close actions in this batch; defaults false"`
	// DryRun, when true, validates and resolves every action but
	// skips mutating ops (click/type/paste/window_*/drag/scroll/
	// move_mouse/set_text/perform_action/clipboard_write). Observing
	// primitives (find_*, wait_*, observe, screenshot, clipboard_read,
	// get_screen_info) still execute against the real desktop so the
	// returned envelope reflects exactly what the agent WOULD have
	// clicked. Per-action results carry dry_run:true and resolved
	// coords/targets under details.
	DryRun bool `json:"dry_run,omitempty" jsonschema:"validate and resolve actions but skip mutating ops"`
	// ResumeFrom skips actions 0..(ResumeFrom-1) and starts execution
	// at the named index. Useful for resuming a batch that was
	// previously yielded (the BatchResult carries the last completed
	// index; agents re-submit with resume_from=lastCompleted+1).
	// Skipped actions are logged to the audit trail with skipped:true.
	ResumeFrom int `json:"resume_from,omitempty" jsonschema:"skip actions 0..(N-1) and resume at index N"`
	// BatchID is an opaque identifier that ties every audit-log line
	// from this batch together. Generated automatically when empty.
	BatchID string `json:"batch_id,omitempty" jsonschema:"opaque id tying audit-log lines for this batch together"`
	// RespectUser, when true, enables yield-to-human behavior for this
	// batch. The CLI's --respect-user flag and MCP-server interactive
	// mode toggle this. Defaults false at the type level so library
	// tests stay deterministic; the CLI layer sets it to the resolved
	// config value.
	RespectUser bool `json:"respect_user,omitempty" jsonschema:"yield batch execution to the human when they drive the desktop"`
	// QuietMS overrides DefaultQuietMS. Precedence: batch field > flag
	// > default.
	QuietMS int `json:"quiet_ms,omitempty" jsonschema:"resume after this many ms of no user input (default 1500)"`
	// YieldTimeoutMS overrides DefaultYieldTimeoutMS. Precedence:
	// batch field > flag > default.
	YieldTimeoutMS int `json:"yield_timeout_ms,omitempty" jsonschema:"abort batch after this many ms of continuous user input (default 30000)"`
}

type Action struct {
	Type       string                 `json:"type"`
	Target     window.Target          `json:"target,omitzero"`
	Point      contract.Point         `json:"point,omitzero"`
	From       contract.Point         `json:"from,omitzero"`
	To         contract.Point         `json:"to,omitzero"`
	Button     string                 `json:"button,omitempty"`
	Count      int                    `json:"count,omitempty"`
	Direction  string                 `json:"direction,omitempty"`
	Amount     int                    `json:"amount,omitempty"`
	Text       string                 `json:"text,omitempty"`
	Key        string                 `json:"key,omitempty"`
	ElementID  string                 `json:"element_id,omitempty"`
	Action     string                 `json:"action,omitempty"`
	DurationMS int                    `json:"duration_ms,omitempty"`
	Screenshot screen.CaptureRequest  `json:"screenshot,omitzero"`
	Details    map[string]interface{} `json:"details,omitempty"`

	// find_* inputs (task-2). Empty for action types that do not use
	// pixel-driven targeting. Accepts the v0.1/v0.2 bare-bounds shape
	// `{x,y,width,height}` (screen-space) AND the task-12 extended
	// shape `{...,space:"window"|"window_frame"|"monitor",target?,
	// monitor_index?}` for in-window or per-monitor OCR / template /
	// color regions. The region is resolved to screen-space before
	// X11 capture; downstream candidate bounds and coord_map continue
	// to report absolute screen coordinates.
	Region        contract.RegionRef `json:"region,omitzero"`
	Query         string             `json:"query,omitempty"`
	Lang          string             `json:"lang,omitempty"`
	CaseSensitive bool               `json:"case_sensitive,omitempty"`
	Regex         bool               `json:"regex,omitempty"`
	MinConfidence float64            `json:"min_confidence,omitempty"`
	// OCR preprocessing + Tesseract tunables (task-8). Defaults are
	// bit-for-bit identical to the pre-task-8 behavior: Preprocess="" is
	// treated as "auto" by FindText, which only mutates pixels when the
	// region mean luminance falls below darkThemeLuminanceThreshold;
	// PSM/OEM=0 omit the flag so Tesseract uses its compiled defaults.
	Preprocess   string    `json:"preprocess,omitempty" jsonschema:"OCR preprocess mode: auto (default), invert, binarize, or none"`
	PSM          int       `json:"psm,omitempty" jsonschema:"Tesseract page segmentation mode (0..13); 0 omits the flag"`
	OEM          int       `json:"oem,omitempty" jsonschema:"Tesseract OCR engine mode (0..3); 0 omits the flag"`
	TemplatePath string    `json:"template_path,omitempty"`
	Threshold    float64   `json:"threshold,omitempty"`
	Scales       []float64 `json:"scales,omitempty"`
	Color        string    `json:"color,omitempty"`
	Tolerance    int       `json:"tolerance,omitempty"`
	MinArea      int       `json:"min_area,omitempty"`

	// Strict flag for click_text / click_image. When true and multiple
	// candidates pass min_confidence the helper fails with
	// TARGET_AMBIGUOUS.
	Strict bool `json:"strict,omitempty"`

	// As stores the highest-confidence find candidate into a named slot
	// for later target_slot reference within the same batch.
	As string `json:"as,omitempty"`

	// TargetSlot, when set on a click/move/drag, resolves the target
	// point to the center of the named slot's bounds.
	TargetSlot string `json:"target_slot,omitempty"`

	// Window-verb fields (task-4). Used by window_move, window_resize,
	// window_workspace, and window_maximize. Empty when the action
	// type does not require them. X/Y are screen-space coordinates for
	// window_move; Width/Height are pixels for window_resize.
	X      int    `json:"x,omitempty"`
	Y      int    `json:"y,omitempty"`
	Width  int    `json:"width,omitempty"`
	Height int    `json:"height,omitempty"`
	Index  int    `json:"index,omitempty" jsonschema:"workspace index for window_workspace"`
	Axis   string `json:"axis,omitempty" jsonschema:"both, horz, or vert; window_maximize"`

	// Wait-condition fields (task-3). Empty for action types that do
	// not use them. Match is the window selector for wait_for_window
	// (mirrors Action.Target but kept separate so the JSON shape on
	// the wire matches the contract spec). Present/Focused are
	// optional pointer booleans so an explicit false is distinguishable
	// from absent. PollMS, TimeoutMS, Mode, StableMS configure cadence
	// for wait_for_window, wait_for_pixel_change, and wait_for_text.
	Match     contract.WindowTarget `json:"match,omitzero" jsonschema:"window selector for wait_for_window"`
	Present   *bool                 `json:"present,omitempty" jsonschema:"wait for presence (true, default) or absence (false)"`
	Focused   *bool                 `json:"focused,omitempty" jsonschema:"require the matched window to be focused"`
	TimeoutMS int                   `json:"timeout_ms,omitempty" jsonschema:"per-action wait timeout in milliseconds"`
	PollMS    int                   `json:"poll_ms,omitempty" jsonschema:"poll cadence in milliseconds"`
	Mode      string                `json:"mode,omitempty" jsonschema:"wait_for_pixel_change mode: any or stable"`
	StableMS  int                   `json:"stable_ms,omitempty" jsonschema:"stable_ms threshold for wait_for_pixel_change mode=stable"`

	// Clipboard/text-input fields (task-5).
	//   Via — type_text routing: xtest, paste, or auto (default auto).
	//   Selection — clipboard_read/write target: clipboard (default), primary, or both (write only).
	//   Mime — clipboard_read/write MIME: text/plain (default) or text/uri-list.
	//   Method — paste action method: key (default; ctrl+v) or insert (shift+insert).
	Via       string `json:"via,omitempty" jsonschema:"type_text route: xtest, paste, or auto (default auto)"`
	Selection string `json:"selection,omitempty" jsonschema:"clipboard selection: clipboard, primary, or both"`
	Mime      string `json:"mime,omitempty" jsonschema:"clipboard MIME: text/plain or text/uri-list"`
	Method    string `json:"method,omitempty" jsonschema:"paste method: key (ctrl+v) or insert (shift+insert)"`
	Content   string `json:"content,omitempty" jsonschema:"clipboard_write content"`
}

type BatchResult struct {
	// SchemaVersion echoes the negotiated schema version back to the
	// caller. Always set to contract.SchemaVersion on success.
	SchemaVersion string                     `json:"schema_version"`
	Results       []contract.ActionResult    `json:"results"`
	Screenshot    *contract.ScreenshotResult `json:"screenshot,omitempty"`
	Observe       *contract.ObserveResult    `json:"observe,omitempty"`
	// BatchID echoes the audit-log batch identifier. Always set,
	// generated when not provided by the caller.
	BatchID string `json:"batch_id,omitempty"`
	// DryRun mirrors ActionBatch.DryRun on the response so agents can
	// confirm what they got back.
	DryRun bool `json:"dry_run,omitempty"`
	// LastCompletedActionIndex is the index (0-based) of the final
	// action that executed (or was skipped via resume_from) in this
	// batch. -1 when nothing executed (e.g. immediate yield abort
	// before action 0).
	LastCompletedActionIndex int `json:"last_completed_action_index"`
	// YieldEvents collects every user input event observed during
	// this batch. Empty when --respect-user was off or no events
	// were seen.
	YieldEvents []YieldEvent `json:"yield_events,omitempty"`
}

// YieldEvent is one user-input observation surfaced to the caller in
// BatchResult.YieldEvents. Shape matches the audit-log YieldSummary
// so agents can correlate the two.
type YieldEvent struct {
	TS        time.Time `json:"ts"`
	DeviceID  int       `json:"device_id"`
	SourceID  int       `json:"source_id"`
	EventType string    `json:"event_type"`
}

// Mutating reports whether the action changes desktop state when
// executed. In dry-run mode the executor invokes the action only when
// this returns false (or the action is the find-then-act hybrid
// click_text / click_image, which always does its find phase and
// records the resolved coords, but skips the click).
//
// Classification:
//
//	Observing (returns false — runs in dry-run):
//	  observe, screenshot, find_text, find_image, find_color,
//	  wait, wait_for_window, wait_for_pixel_change, wait_for_text,
//	  clipboard_read
//
//	Mutating (returns true — skipped in dry-run):
//	  click, double_click, move_mouse, drag, scroll, type_text, paste,
//	  press_key, set_text, perform_action, window_move, window_resize,
//	  window_raise, window_minimize, window_maximize, window_workspace,
//	  window_close, clipboard_write, focus_window
//
//	Hybrid (handled specially in Run): click_text, click_image — the
//	  find phase always runs (observing); the click phase is gated by
//	  dry-run.
//
// Note: focus_window is classified as mutating because stealing focus
// is a visible desktop state change (other windows see FocusIn/FocusOut
// events). In dry-run the resolved target is reported but no actual
// focus call fires.
func (a Action) Mutating() bool {
	switch a.Type {
	case "click", "double_click", "move_mouse", "move", "drag", "scroll",
		"type_text", "paste", "press_key", "set_text", "perform_action",
		"window_move", "window_resize", "window_raise", "window_minimize",
		"window_maximize", "window_workspace", "window_close",
		"clipboard_write", "focus_window", "focus":
		return true
	}
	return false
}

func Run(ctx context.Context, batch ActionBatch) (BatchResult, error) {
	if err := contract.ValidateSchemaVersion(batch.SchemaVersion); err != nil {
		return BatchResult{}, err
	}
	// Negative resume_from is the only structurally invalid value;
	// resume_from >= len(actions) (including the empty-actions case)
	// is treated as a benign no-op success path so agents stitching
	// resume cycles can re-submit without branching on edge cases.
	// The response still carries schema_version + results:[] +
	// last_completed_action_index=-1 (or the last skipped index when
	// resume_from > 0) so callers can iterate the envelope uniformly.
	if batch.ResumeFrom < 0 {
		return BatchResult{}, contract.Validation("RESUME_FROM_OUT_OF_RANGE", "resume_from must be >= 0", map[string]any{"resume_from": batch.ResumeFrom, "actions": len(batch.Actions)})
	}
	if batch.BatchID == "" {
		batch.BatchID = newBatchID()
	}
	// When --audit-full-payloads is on, persist the original batch
	// inputs (clipboard content scrubbed inside the audit package)
	// before execution starts. Doing it up front ensures the manifest
	// exists for `audit replay` even if a later action errors out and
	// short-circuits the loop.
	writeBatchPayload(batch)
	bctx := imageutil.NewBatchContext()
	// out is constructed up front so EVERY success-path return —
	// including the empty-actions and resume_from-past-end no-op
	// paths — carries a populated envelope: SchemaVersion echoes the
	// negotiated contract version, Results is a non-nil slice (so
	// JSON serializes as [] not null), and LastCompletedActionIndex
	// defaults to -1 per the struct's documented "nothing executed"
	// convention. Regression guard: task-32 fixed a v0.3.3 bug where
	// an early return shipped a zero-value BatchResult.
	out := BatchResult{
		SchemaVersion:            contract.SchemaVersion,
		Results:                  []contract.ActionResult{},
		BatchID:                  batch.BatchID,
		DryRun:                   batch.DryRun,
		LastCompletedActionIndex: -1,
	}
	// Empty actions: no audit records, no yield watcher spin-up, just
	// echo the envelope and return success. Agents that submit an
	// empty batch are typically probing schema negotiation or running
	// a no-op resume cycle; treating it as a hard error broke that
	// path.
	if len(batch.Actions) == 0 {
		return out, nil
	}

	// Activity setup: when RespectUser is on AND the platform exposes a
	// user-activity watcher we start it and inspect events between actions.
	// Server/headless callers (no TTY) pass RespectUser=false so the
	// watcher is never spawned. The watcher is best-effort: a failed
	// Start logs to stderr and continues without yield.
	var yieldCh <-chan platform.ActivityEvent
	if batch.RespectUser {
		if watcher, ok := platform.Current().Activity(); ok {
			if available, _ := watcher.Available(); available {
				events, stop, err := watcher.Start(ctx)
				if err != nil {
					fmt.Fprintf(os.Stderr, "mycomputer: yield watcher start failed: %v\n", err)
				} else {
					yieldCh = events
					if stop != nil {
						defer stop()
					}
				}
			} else {
				fmt.Fprintln(os.Stderr, "mycomputer: --respect-user requested but activity watcher not available; yield disabled")
			}
		} else {
			fmt.Fprintln(os.Stderr, "mycomputer: --respect-user requested but activity watcher not available; yield disabled")
		}
	}
	quietMS := batch.QuietMS
	if quietMS <= 0 {
		quietMS = DefaultQuietMS
	}
	timeoutMS := batch.YieldTimeoutMS
	if timeoutMS <= 0 {
		timeoutMS = DefaultYieldTimeoutMS
	}

	// resume_from: replay skipped actions to the audit log so agents
	// can stitch the trail across re-submissions. The loop is clamped
	// to len(batch.Actions) so a resume_from past the end of the
	// input array degrades to a benign no-op (the success envelope
	// carries LastCompletedActionIndex from the last skipped slot, or
	// -1 when resume_from is 0). Without clamping, batch.Actions[i]
	// would panic on out-of-range index.
	replayCap := batch.ResumeFrom
	if replayCap > len(batch.Actions) {
		replayCap = len(batch.Actions)
	}
	for i := 0; i < replayCap; i++ {
		writeAudit(audit.Record{
			BatchID:     batch.BatchID,
			ActionIndex: i,
			Type:        batch.Actions[i].Type,
			OK:          true,
			Skipped:     true,
			DryRun:      batch.DryRun,
		})
		out.LastCompletedActionIndex = i
	}

	for idx := batch.ResumeFrom; idx < len(batch.Actions); idx++ {
		action := batch.Actions[idx]
		if err := ctx.Err(); err != nil {
			return out, contract.Cancelled("action batch cancelled")
		}
		// Yield check before each action. If user input is observed
		// AND --respect-user is on, drain until quiet for quietMS or
		// abort after timeoutMS.
		if yieldCh != nil {
			if err := waitForQuiet(ctx, yieldCh, &out, time.Duration(quietMS)*time.Millisecond, time.Duration(timeoutMS)*time.Millisecond); err != nil {
				writeAudit(audit.Record{
					BatchID:     batch.BatchID,
					ActionIndex: idx,
					Type:        action.Type,
					OK:          false,
					Error:       err.Error(),
					Skipped:     true,
					DryRun:      batch.DryRun,
				})
				return out, err
			}
		}

		started := time.Now()
		rec, res, runErr := dispatchAction(ctx, batch, action, idx, bctx, &out)
		rec.BatchID = batch.BatchID
		rec.ActionIndex = idx
		rec.Type = action.Type
		rec.DryRun = batch.DryRun
		rec.ElapsedMS = time.Since(started).Milliseconds()
		if runErr != nil {
			rec.OK = false
			rec.Error = runErr.Error()
			writeAudit(rec)
			return out, runErr
		}
		rec.OK = true
		if res.Backend != "" {
			rec.Backend = res.Backend
		}
		writeAudit(rec)

		out.Results = append(out.Results, res)
		out.LastCompletedActionIndex = idx
	}
	return out, nil
}

// waitForQuiet pauses execution while the user is actively driving
// the desktop. It blocks reading from yieldCh:
//
//   - On each event: record it to out.YieldEvents, audit the event,
//     and reset the quiet timer.
//   - When no event arrives within `quiet`, return nil — caller may
//     resume.
//   - When events keep arriving past `timeout`, return Cancelled with
//     code YIELDED_TO_USER (exit 6).
//
// The function returns immediately (nil) when no event is pending —
// the common case. yieldCh must be drained between calls so we don't
// over-trigger on stale events.
func waitForQuiet(ctx context.Context, yieldCh <-chan platform.ActivityEvent, out *BatchResult, quiet, timeout time.Duration) error {
	// Non-blocking peek: if no event pending, return immediately.
	var first *platform.ActivityEvent
	select {
	case e, ok := <-yieldCh:
		if !ok {
			return nil
		}
		first = &e
	default:
		return nil
	}
	// We have at least one user event. Record it and start waiting.
	recordYield(out, *first)
	overall := time.NewTimer(timeout)
	defer overall.Stop()
	quietT := time.NewTimer(quiet)
	defer quietT.Stop()
	for {
		select {
		case <-ctx.Done():
			return contract.Cancelled("action batch cancelled while yielded")
		case <-overall.C:
			return contract.NewError(contract.ExitCancelled, "YIELDED_TO_USER", "user continued driving the desktop past yield_timeout_ms", map[string]any{
				"yield_timeout_ms": timeout.Milliseconds(),
				"yield_events":     len(out.YieldEvents),
			})
		case e, ok := <-yieldCh:
			if !ok {
				// Watcher exited mid-wait. Resume.
				return nil
			}
			recordYield(out, e)
			if !quietT.Stop() {
				select {
				case <-quietT.C:
				default:
				}
			}
			quietT.Reset(quiet)
		case <-quietT.C:
			return nil
		}
	}
}

func recordYield(out *BatchResult, e platform.ActivityEvent) {
	ev := YieldEvent{TS: e.TS, DeviceID: e.DeviceID, SourceID: e.SourceID, EventType: e.Kind}
	out.YieldEvents = append(out.YieldEvents, ev)
	writeAudit(audit.Record{
		BatchID:     out.BatchID,
		ActionIndex: out.LastCompletedActionIndex + 1,
		Type:        "yield.observed",
		OK:          true,
		YieldEvent: &audit.YieldSummary{
			DeviceID:  e.DeviceID,
			SourceID:  e.SourceID,
			EventType: e.Kind,
		},
	})
}

// writeAudit is the best-effort audit appender used by Run. Failures
// surface on stderr (when --verbose is set the caller already routes
// stderr appropriately) but never block execution.
//
// When the active audit writer is in FullPayloads mode the record is
// tagged with payload_ref:<batch_id> so the JSONL stream points at the
// per-batch manifest written under <audit_dir>/payloads/.
func writeAudit(rec audit.Record) {
	if auditWriter == nil {
		return
	}
	if auditWriter.FullPayloads && rec.BatchID != "" && rec.PayloadRef == "" {
		rec.PayloadRef = rec.BatchID
	}
	if err := auditWriter.Append(rec); err != nil {
		fmt.Fprintf(os.Stderr, "mycomputer: audit append failed: %v\n", err)
	}
}

// writeBatchPayload persists the original ActionBatch JSON under
// <audit_dir>/payloads/<batch_id>.json when FullPayloads is enabled.
// Clipboard `content` is scrubbed by the audit package before the file
// is written — the privacy invariant on clipboard content is honored
// regardless of this flag. Failures surface on stderr; they never
// block execution.
func writeBatchPayload(batch ActionBatch) {
	if auditWriter == nil || !auditWriter.FullPayloads {
		return
	}
	raw, err := json.Marshal(batch)
	if err != nil {
		fmt.Fprintf(os.Stderr, "mycomputer: audit payload marshal failed: %v\n", err)
		return
	}
	if err := auditWriter.WriteBatchPayload(batch.BatchID, raw); err != nil {
		fmt.Fprintf(os.Stderr, "mycomputer: audit payload write failed: %v\n", err)
	}
}

// newBatchID returns a short random id for use when ActionBatch.BatchID
// is empty. 16 hex chars (8 random bytes) — plenty for grep/jq lookup.
func newBatchID() string {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return fmt.Sprintf("ts-%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b[:])
}

// dispatchAction executes a single Action against the desktop and
// returns the resulting ActionResult plus an audit Record with the
// resolved coords/target filled in (the executor stamps batch_id /
// action_index / type / dry_run / elapsed afterward). The split
// keeps Run's body small while preserving the per-type semantics.
func dispatchAction(ctx context.Context, batch ActionBatch, action Action, idx int, bctx *imageutil.BatchContext, out *BatchResult) (audit.Record, contract.ActionResult, error) {
	rec := audit.Record{}
	// Pre-resolve coords/target for the audit record so dry-run
	// previews include exactly what would have been clicked. Resolution
	// is READ-ONLY — observing the window/monitor lists is safe even
	// in dry-run mode. We hydrate the ResolveContext from the action's
	// participating points so window-space and monitor-space resolution
	// produces real screen coordinates (not just the zero-context
	// screen-space short-circuit). Failures are non-fatal here: the
	// dry-run preview surfaces resolved_coords:null instead of
	// surfacing a confusing error from a path the caller didn't ask
	// to execute. The downstream resolvePoint call in the live path
	// re-runs resolution against a fresh context and still returns
	// the canonical error to the caller when something is truly off.
	if !pointZero(action.Point) {
		rctx, err := input.ResolveContextFor(ctx, pointResolveCandidates(action)...)
		if err == nil {
			if x, y, err := contract.Resolve(action.Point, rctx); err == nil {
				rec.ResolvedCoords = &audit.Point{X: x, Y: y}
			}
		}
	}
	if !action.Target.Empty() {
		rec.Target = map[string]any{
			"id":    action.Target.ID,
			"title": action.Target.Title,
			"class": action.Target.Class,
			"pid":   action.Target.PID,
		}
	}

	// Dry-run gate for purely-mutating types: emit a synthetic
	// dry-run result envelope with the resolved coords/target and
	// skip the real side effect.
	if batch.DryRun && action.Mutating() && action.Type != "click_text" && action.Type != "click_image" {
		details := map[string]any{"dry_run": true}
		if rec.ResolvedCoords != nil {
			details["resolved_coords"] = map[string]any{"x": rec.ResolvedCoords.X, "y": rec.ResolvedCoords.Y}
		}
		if rec.Target != nil {
			details["resolved_target"] = rec.Target
		}
		// type_text preview: surface which route ("xtest" | "paste")
		// the auto policy would have chosen, plus the stable reason
		// tag. This is a read-only computation on text content + IME
		// status, so it's safe in dry-run. Explicit via:"xtest" or
		// via:"paste" is echoed back with a synthetic reason.
		if action.Type == "type_text" {
			via, reason := dryRunTypeTextRoute(action.Text, action.Via)
			details["via"] = via
			details["route_reason"] = reason
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "dry-run", Details: details}, nil
	}

	switch action.Type {
	case "focus_window", "focus":
		win, err := window.Focus(ctx, action.Target)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "x11.EWMH", Details: map[string]any{"window": win}}, nil
	case "move_mouse", "move":
		point, err := resolvePoint(action.Point, action.TargetSlot, bctx)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		if err := input.Move(ctx, point); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest"}, nil
	case "click":
		point, err := resolvePoint(action.Point, action.TargetSlot, bctx)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		if err := input.Click(ctx, input.ClickRequest{Point: point, Button: action.Button, Count: action.Count}); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest"}, nil
	case "double_click":
		point, err := resolvePoint(action.Point, action.TargetSlot, bctx)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		if err := input.Click(ctx, input.ClickRequest{Point: point, Button: action.Button, Count: 2}); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest"}, nil
	case "drag":
		if err := input.Drag(ctx, input.DragRequest{From: action.From, To: action.To, Button: action.Button, DurationMS: action.DurationMS}); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest"}, nil
	case "scroll":
		if err := input.Scroll(ctx, input.ScrollRequest{Point: action.Point, Direction: action.Direction, Amount: action.Amount}); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest"}, nil
	case "type_text":
		res, err := input.TypeTextWith(ctx, input.TypeTextRequest{Text: action.Text, Via: action.Via})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		details := map[string]any{"via": res.Via}
		if res.Via == input.TypeTextViaPaste {
			details["clipboard_restored"] = res.ClipboardRestored
		}
		if res.IMEActive {
			details["ime_active"] = true
			if res.IMEEngine != "" {
				details["ime_engine"] = res.IMEEngine
			}
		}
		backend := "XTest"
		if res.Via == input.TypeTextViaPaste {
			backend = "x11.clipboard"
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: backend, Details: details}, nil
	case "clipboard_read":
		// clipboard_read is OBSERVING — runs in dry-run because the
		// agent wants to see what's on the clipboard before deciding
		// to overwrite it. The content IS surfaced in the result
		// envelope (agents need it), but is NEVER written to the
		// audit log — only bytes/mime/selection appear there.
		r, err := clipboard.Read(ctx, action.Selection, action.Mime)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		rec.Clipboard = &audit.ClipboardSummary{Selection: r.Selection, Mime: r.Mime, Bytes: r.Bytes}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "x11.clipboard", Details: map[string]any{
			"content":   r.Content,
			"mime":      r.Mime,
			"selection": r.Selection,
			"bytes":     r.Bytes,
		}}, nil
	case "clipboard_write":
		w, err := clipboard.Write(ctx, action.Selection, action.Content, action.Mime)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		// Audit redaction: bytes + mime + selection only — content
		// must NEVER appear in the audit log (see task-6 contract).
		rec.Clipboard = &audit.ClipboardSummary{Selection: w.Selection, Mime: w.Mime, Bytes: w.Bytes}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "x11.clipboard", Details: map[string]any{
			"selection": w.Selection,
			"mime":      w.Mime,
			"bytes":     w.Bytes,
		}}, nil
	case "paste":
		method := action.Method
		if method == "" {
			method = "key"
		}
		var chord string
		switch method {
		case "key":
			chord = "ctrl+v"
		case "insert":
			chord = "shift+insert"
		default:
			return rec, contract.ActionResult{}, contract.Validation("PASTE_METHOD_INVALID", "paste method must be key or insert", map[string]any{"method": method})
		}
		if action.Selection != "" && action.Selection != clipboard.SelectionClipboard {
			return rec, contract.ActionResult{}, contract.Validation("CLIPBOARD_SELECTION_INVALID", "paste only supports the clipboard selection", map[string]any{"selection": action.Selection})
		}
		if err := input.PressKey(ctx, chord); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest", Details: map[string]any{"method": method, "chord": chord}}, nil
	case "press_key":
		if err := input.PressKey(ctx, action.Key); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest"}, nil
	case "set_text":
		if action.ElementID == "" {
			return rec, contract.ActionResult{}, contract.Validation("ELEMENT_ID_REQUIRED", "set_text requires an AT-SPI element_id", nil)
		}
		if err := a11y.SetText(ctx, action.ElementID, action.Text); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "at-spi"}, nil
	case "perform_action":
		if action.ElementID == "" {
			return rec, contract.ActionResult{}, contract.Validation("ELEMENT_ID_REQUIRED", "perform_action requires an AT-SPI element_id", nil)
		}
		if err := a11y.PerformAction(ctx, action.ElementID, action.Action); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "at-spi"}, nil
	case "wait":
		duration := time.Duration(action.DurationMS) * time.Millisecond
		if duration <= 0 {
			duration = 500 * time.Millisecond
		}
		select {
		case <-ctx.Done():
			return rec, contract.ActionResult{}, contract.Cancelled("action wait cancelled")
		case <-time.After(duration):
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "timer"}, nil
	case "screenshot":
		shot, err := screen.Capture(ctx, action.Screenshot)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		out.Screenshot = &shot
		details := map[string]any{"screenshot": shot}
		if shot.RegionClamped {
			details["region_clamped"] = true
			if shot.OriginalRegion != nil {
				details["original_region"] = *shot.OriginalRegion
			}
			if shot.ClampedRegion != nil {
				details["clamped_region"] = *shot.ClampedRegion
			}
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: shot.Backend, Details: details}, nil
	case "observe":
		obs, err := Observe(ctx, false)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		out.Observe = &obs
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "mixed"}, nil
	case "find_text":
		result, err := runFindText(ctx, bctx, action)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		storeSlot(bctx, action.As, result)
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "ocr_tesseract", Details: findResultDetails(result)}, nil
	case "find_image":
		result, err := runFindImage(ctx, action)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		storeSlot(bctx, action.As, result)
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "template_match", Details: findResultDetails(result)}, nil
	case "find_color":
		result, err := runFindColor(ctx, action)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		storeSlot(bctx, action.As, result)
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "color", Details: findResultDetails(result)}, nil
	case "click_text":
		// Hybrid: find phase always runs (observing); click phase
		// skipped in dry-run. Result envelope still includes the
		// matched candidate's bounds + resolved click coord.
		result, err := runFindText(ctx, bctx, action)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		cand, err := pickClickCandidate(result.Candidates, action.MinConfidence, action.Strict, "text")
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		storeSlot(bctx, action.As, result)
		click := centerOf(cand)
		rec.ResolvedCoords = &audit.Point{X: click.X, Y: click.Y}
		if batch.DryRun {
			return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "dry-run", Details: map[string]any{
				"dry_run":         true,
				"matched":         cand,
				"resolved_coords": map[string]any{"x": click.X, "y": click.Y},
			}}, nil
		}
		if err := input.Click(ctx, input.ClickRequest{Point: click, Button: action.Button, Count: max1(action.Count)}); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest", Details: map[string]any{"matched": cand}}, nil
	case "click_image":
		// Hybrid: same dry-run semantics as click_text.
		result, err := runFindImage(ctx, action)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		cand, err := pickClickCandidate(result.Candidates, action.MinConfidence, action.Strict, "image")
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		storeSlot(bctx, action.As, result)
		click := centerOf(cand)
		rec.ResolvedCoords = &audit.Point{X: click.X, Y: click.Y}
		if batch.DryRun {
			return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "dry-run", Details: map[string]any{
				"dry_run":         true,
				"matched":         cand,
				"resolved_coords": map[string]any{"x": click.X, "y": click.Y},
			}}, nil
		}
		if err := input.Click(ctx, input.ClickRequest{Point: click, Button: action.Button, Count: max1(action.Count)}); err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{Action: action.Type, OK: true, Backend: "XTest", Details: map[string]any{"matched": cand}}, nil
	case "window_move":
		res, err := window.Move(ctx, window.MoveRequest{Target: action.Target, X: action.X, Y: action.Y})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, windowActionResult(action.Type, res), nil
	case "window_resize":
		res, err := window.Resize(ctx, window.ResizeRequest{Target: action.Target, Width: action.Width, Height: action.Height})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, windowActionResult(action.Type, res), nil
	case "window_raise":
		res, err := window.Raise(ctx, action.Target)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, windowActionResult(action.Type, res), nil
	case "window_minimize":
		res, err := window.Minimize(ctx, action.Target)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, windowActionResult(action.Type, res), nil
	case "window_maximize":
		res, err := window.Maximize(ctx, window.MaximizeRequest{Target: action.Target, Axis: action.Axis})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, windowActionResult(action.Type, res), nil
	case "window_workspace":
		res, err := window.Workspace(ctx, window.WorkspaceRequest{Target: action.Target, Index: action.Index})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, windowActionResult(action.Type, res), nil
	case "window_close":
		if !batch.AllowClose {
			return rec, contract.ActionResult{}, contract.Precondition("PRECONDITION_CLOSE_NOT_ALLOWED", "window_close requires allow_close:true on the batch or --allow-close on the CLI", map[string]any{"target": action.Target})
		}
		res, err := window.Close(ctx, action.Target)
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, windowActionResult(action.Type, res), nil
	case "wait_for_window":
		res, err := wait.WaitForWindow(ctx, wait.WindowRequest{
			Match:     action.Match,
			Present:   action.Present,
			Focused:   action.Focused,
			TimeoutMS: action.TimeoutMS,
			PollMS:    action.PollMS,
		})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		return rec, contract.ActionResult{
			Action:  action.Type,
			OK:      true,
			Backend: "x11.EWMH",
			Details: map[string]any{
				"matched":    res.Matched,
				"polls":      res.Polls,
				"elapsed_ms": res.ElapsedMS,
				"last_state": res.LastState,
			},
		}, nil
	case "wait_for_pixel_change":
		res, err := wait.WaitForPixelChange(ctx, wait.PixelRequest{
			Region:    action.Region,
			Threshold: action.Threshold,
			TimeoutMS: action.TimeoutMS,
			PollMS:    action.PollMS,
			Mode:      action.Mode,
			StableMS:  action.StableMS,
		})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		details := map[string]any{
			"changed":    res.Changed,
			"diff":       res.Diff,
			"polls":      res.Polls,
			"elapsed_ms": res.ElapsedMS,
			"last_state": res.LastState,
		}
		applyPixelClampDetails(details, res)
		return rec, contract.ActionResult{
			Action:  action.Type,
			OK:      true,
			Backend: "x11.GetImage",
			Details: details,
		}, nil
	case "wait_for_text":
		res, err := wait.WaitForText(ctx, wait.TextRequest{
			Query:         action.Query,
			Region:        action.Region,
			Present:       action.Present,
			TimeoutMS:     action.TimeoutMS,
			PollMS:        action.PollMS,
			MinConfidence: action.MinConfidence,
			Lang:          action.Lang,
			CaseSensitive: action.CaseSensitive,
			Regex:         action.Regex,
		})
		if err != nil {
			return rec, contract.ActionResult{}, err
		}
		details := map[string]any{
			"found":      res.Found,
			"candidate":  res.Candidate,
			"polls":      res.Polls,
			"elapsed_ms": res.ElapsedMS,
			"last_state": res.LastState,
		}
		applyTextClampDetails(details, res)
		return rec, contract.ActionResult{
			Action:  action.Type,
			OK:      true,
			Backend: "ocr_tesseract",
			Details: details,
		}, nil
	default:
		return rec, contract.ActionResult{}, contract.Validation("ACTION_UNSUPPORTED", "action type is unsupported", map[string]any{"type": action.Type})
	}
}

// resolveRegionDetailed returns the effective screen-space region for
// a find action along with optional clamp metadata. An explicit
// RegionRef is translated through screen.ResolveCaptureRegionDetailed
// (handles window-space and monitor-space, and surfaces the clamp
// flag); an empty region falls back to the focused-window bounds, then
// to the full screen. The returned Bounds is always absolute
// screen-space so downstream find_* candidate offsets and coord_map
// values remain consistent regardless of the input space. Empty region
// inputs always report Clamped=false because no caller-supplied
// rectangle was shrunk — the fallback path is always a deliberate
// full-rect grab.
func resolveRegionDetailed(ctx context.Context, region contract.RegionRef) (contract.ResolveResult, error) {
	if !region.Empty() {
		return screen.ResolveCaptureRegionDetailed(ctx, region)
	}
	if focused, err := window.Focused(ctx); err == nil && focused != nil && !focused.Bounds.Empty() {
		return contract.ResolveResult{Bounds: focused.Bounds}, nil
	}
	info, err := screen.Info(ctx)
	if err != nil {
		return contract.ResolveResult{}, err
	}
	return contract.ResolveResult{Bounds: info.Bounds}, nil
}

func runFindText(ctx context.Context, bctx *imageutil.BatchContext, action Action) (contract.FindResult, error) {
	regionRes, err := resolveRegionDetailed(ctx, action.Region)
	if err != nil {
		return contract.FindResult{}, err
	}
	img, capture, err := screen.CaptureRGBA(ctx, regionRes.Bounds)
	if err != nil {
		return contract.FindResult{}, err
	}
	result, err := imageutil.FindText(ctx, bctx, capture, img, imageutil.FindTextRequest{
		Region:        capture,
		Query:         action.Query,
		Lang:          action.Lang,
		CaseSensitive: action.CaseSensitive,
		MinConfidence: action.MinConfidence,
		Regex:         action.Regex,
		Preprocess:    action.Preprocess,
		PSM:           action.PSM,
		OEM:           action.OEM,
	})
	if err != nil {
		return contract.FindResult{}, err
	}
	annotateFindClamp(&result, regionRes)
	if len(result.Candidates) == 0 {
		return result, contract.NotFound("TARGET_NOT_FOUND", "find_text returned no candidates", map[string]any{"query": action.Query, "region": capture})
	}
	return result, nil
}

func runFindImage(ctx context.Context, action Action) (contract.FindResult, error) {
	regionRes, err := resolveRegionDetailed(ctx, action.Region)
	if err != nil {
		return contract.FindResult{}, err
	}
	img, capture, err := screen.CaptureRGBA(ctx, regionRes.Bounds)
	if err != nil {
		return contract.FindResult{}, err
	}
	result, err := imageutil.FindImage(ctx, capture, img, imageutil.FindImageRequest{
		TemplatePath: action.TemplatePath,
		Region:       capture,
		Threshold:    action.Threshold,
		Scales:       action.Scales,
	})
	if err != nil {
		return contract.FindResult{}, err
	}
	annotateFindClamp(&result, regionRes)
	if len(result.Candidates) == 0 {
		return result, contract.NotFound("TARGET_NOT_FOUND", "find_image returned no candidates", map[string]any{"template_path": action.TemplatePath, "region": capture})
	}
	return result, nil
}

func runFindColor(ctx context.Context, action Action) (contract.FindResult, error) {
	regionRes, err := resolveRegionDetailed(ctx, action.Region)
	if err != nil {
		return contract.FindResult{}, err
	}
	img, capture, err := screen.CaptureRGBA(ctx, regionRes.Bounds)
	if err != nil {
		return contract.FindResult{}, err
	}
	req := imageutil.FindColorRequest{
		Region:    capture,
		Color:     action.Color,
		Tolerance: action.Tolerance,
		MinArea:   action.MinArea,
	}
	if !pointZero(action.Point) {
		p := action.Point
		req.Point = &p
	}
	result, err := imageutil.FindColor(ctx, capture, img, req)
	if err != nil {
		return contract.FindResult{}, err
	}
	annotateFindClamp(&result, regionRes)
	if len(result.Candidates) == 0 {
		return result, contract.NotFound("TARGET_NOT_FOUND", "find_color returned no candidates", map[string]any{"color": action.Color, "region": capture})
	}
	return result, nil
}

// annotateFindClamp copies the clamp metadata from a ResolveResult onto
// a FindResult so the find_* action response carries region_clamped,
// original_region, and clamped_region next to its candidates. No-op
// when the resolve did not clamp.
func annotateFindClamp(result *contract.FindResult, res contract.ResolveResult) {
	if !res.Clamped {
		return
	}
	orig := res.OriginalRegion
	clamped := res.ClampedRegion
	result.RegionClamped = true
	result.OriginalRegion = &orig
	result.ClampedRegion = &clamped
}

// findResultDetails packages a FindResult into an ActionResult.Details
// map, mirroring the existing "find_result" key for backwards compat
// and adding top-level region_clamped/original_region/clamped_region
// keys when the search region was silently shrunk to fit the
// resolved-space bounds. Top-level keys exist alongside the nested
// find_result (which also carries the same fields) so agents that scan
// either layer pick up the clamp.
func findResultDetails(result contract.FindResult) map[string]any {
	details := map[string]any{"find_result": result}
	if result.RegionClamped {
		details["region_clamped"] = true
		if result.OriginalRegion != nil {
			details["original_region"] = *result.OriginalRegion
		}
		if result.ClampedRegion != nil {
			details["clamped_region"] = *result.ClampedRegion
		}
	}
	return details
}

// applyPixelClampDetails copies clamp metadata from a wait.PixelResult
// onto an ActionResult.Details map so wait_for_pixel_change responses
// surface region_clamped:true plus the original and clamped local
// rectangles. No-op when the resolve did not clamp.
func applyPixelClampDetails(details map[string]any, res wait.PixelResult) {
	if !res.RegionClamped {
		return
	}
	details["region_clamped"] = true
	if res.OriginalRegion != nil {
		details["original_region"] = *res.OriginalRegion
	}
	if res.ClampedRegion != nil {
		details["clamped_region"] = *res.ClampedRegion
	}
}

// applyTextClampDetails mirrors applyPixelClampDetails for
// wait.TextResult.
func applyTextClampDetails(details map[string]any, res wait.TextResult) {
	if !res.RegionClamped {
		return
	}
	details["region_clamped"] = true
	if res.OriginalRegion != nil {
		details["original_region"] = *res.OriginalRegion
	}
	if res.ClampedRegion != nil {
		details["clamped_region"] = *res.ClampedRegion
	}
}

func pickClickCandidate(cands []contract.FindCandidate, minConf float64, strict bool, what string) (contract.FindCandidate, error) {
	if len(cands) == 0 {
		return contract.FindCandidate{}, contract.NotFound("TARGET_NOT_FOUND", "click target not found", map[string]any{"what": what})
	}
	if strict {
		var passing []contract.FindCandidate
		for _, c := range cands {
			if c.Confidence >= minConf {
				passing = append(passing, c)
			}
		}
		if len(passing) > 1 {
			return contract.FindCandidate{}, contract.Precondition("TARGET_AMBIGUOUS", "multiple candidates above min_confidence", map[string]any{"what": what, "count": len(passing), "min_confidence": minConf})
		}
		if len(passing) == 1 {
			return passing[0], nil
		}
	}
	return cands[0], nil
}

func centerOf(c contract.FindCandidate) contract.Point {
	return contract.Point{
		X:     c.Bounds.X + c.Bounds.Width/2,
		Y:     c.Bounds.Y + c.Bounds.Height/2,
		Space: contract.CoordSpaceScreen,
	}
}

func resolvePoint(point contract.Point, slot string, bctx *imageutil.BatchContext) (contract.Point, error) {
	if slot == "" {
		return point, nil
	}
	cand, ok := bctx.Slot(slot)
	if !ok {
		return contract.Point{}, contract.Validation("TARGET_SLOT_UNKNOWN", "target_slot does not reference a stored find result", map[string]any{"target_slot": slot})
	}
	return centerOf(cand), nil
}

func storeSlot(bctx *imageutil.BatchContext, name string, result contract.FindResult) {
	if name == "" || len(result.Candidates) == 0 {
		return
	}
	bctx.SetSlot(name, result.Candidates[0])
}

func pointZero(p contract.Point) bool {
	return p.X == 0 && p.Y == 0 && p.Space == "" && p.CoordMap == "" && p.Target.Empty() && p.MonitorIndex == nil
}

// windowActionResult packages a window-verb result into the standard
// contract.ActionResult envelope, surfacing the post-op window snapshot
// and any non-fatal warning (e.g. WINDOW_GEOMETRY_REFUSED) under
// details. Result.OK is always true; warnings are advisory.
func windowActionResult(action string, res window.VerbResult) contract.ActionResult {
	details := map[string]any{"window": res.Window}
	if res.Warning != nil {
		details["warning"] = res.Warning
	}
	if len(res.Notes) > 0 {
		details["notes"] = res.Notes
	}
	return contract.ActionResult{Action: action, OK: true, Backend: "x11.EWMH", Details: details}
}

func max1(n int) int {
	if n <= 0 {
		return 1
	}
	return n
}

// RunFindText is the standalone entry point for the find_text MCP tool
// and CLI command. Uses a fresh BatchContext so OCR cache lifetime
// equals the call.
func RunFindText(ctx context.Context, action Action) (contract.FindResult, error) {
	return runFindText(ctx, imageutil.NewBatchContext(), action)
}

// RunFindImage is the standalone entry point for the find_image MCP
// tool and CLI command.
func RunFindImage(ctx context.Context, action Action) (contract.FindResult, error) {
	return runFindImage(ctx, action)
}

// RunFindColor is the standalone entry point for the find_color MCP
// tool and CLI command.
func RunFindColor(ctx context.Context, action Action) (contract.FindResult, error) {
	return runFindColor(ctx, action)
}

// RunWaitForWindow is the standalone entry point for the
// wait_for_window MCP tool and CLI command. Inputs mirror
// wait.WindowRequest exactly so wire shape is identical between the
// batch action and the standalone tool.
func RunWaitForWindow(ctx context.Context, req wait.WindowRequest) (wait.WindowResult, error) {
	return wait.WaitForWindow(ctx, req)
}

// RunWaitForPixelChange is the standalone entry point for the
// wait_for_pixel_change MCP tool and CLI command.
func RunWaitForPixelChange(ctx context.Context, req wait.PixelRequest) (wait.PixelResult, error) {
	return wait.WaitForPixelChange(ctx, req)
}

// RunWaitForText is the standalone entry point for the wait_for_text
// MCP tool and CLI command.
func RunWaitForText(ctx context.Context, req wait.TextRequest) (wait.TextResult, error) {
	return wait.WaitForText(ctx, req)
}

// RunClickText composes find_text + click on the highest-confidence
// candidate. TARGET_NOT_FOUND when nothing matched; TARGET_AMBIGUOUS
// when strict and multiple candidates pass min_confidence.
func RunClickText(ctx context.Context, action Action) (contract.ActionResult, error) {
	bctx := imageutil.NewBatchContext()
	result, err := runFindText(ctx, bctx, action)
	if err != nil {
		return contract.ActionResult{Action: "click_text", OK: false}, err
	}
	cand, err := pickClickCandidate(result.Candidates, action.MinConfidence, action.Strict, "text")
	if err != nil {
		return contract.ActionResult{Action: "click_text", OK: false}, err
	}
	if err := input.Click(ctx, input.ClickRequest{Point: centerOf(cand), Button: action.Button, Count: max1(action.Count)}); err != nil {
		return contract.ActionResult{Action: "click_text", OK: false}, err
	}
	return contract.ActionResult{Action: "click_text", OK: true, Backend: "XTest", Details: map[string]any{"matched": cand}}, nil
}

// RunClickImage composes find_image + click on the highest-confidence
// candidate.
func RunClickImage(ctx context.Context, action Action) (contract.ActionResult, error) {
	result, err := runFindImage(ctx, action)
	if err != nil {
		return contract.ActionResult{Action: "click_image", OK: false}, err
	}
	cand, err := pickClickCandidate(result.Candidates, action.MinConfidence, action.Strict, "image")
	if err != nil {
		return contract.ActionResult{Action: "click_image", OK: false}, err
	}
	if err := input.Click(ctx, input.ClickRequest{Point: centerOf(cand), Button: action.Button, Count: max1(action.Count)}); err != nil {
		return contract.ActionResult{Action: "click_image", OK: false}, err
	}
	return contract.ActionResult{Action: "click_image", OK: true, Backend: "XTest", Details: map[string]any{"matched": cand}}, nil
}

func Observe(ctx context.Context, includeScreenshot bool) (contract.ObserveResult, error) {
	info, err := screen.Info(ctx)
	if err != nil {
		return contract.ObserveResult{}, err
	}
	wins, err := window.List(ctx)
	if err != nil {
		return contract.ObserveResult{}, err
	}
	focused, _ := window.Focused(ctx)
	cursor, _ := screen.Cursor(ctx)
	// Pass the X11 window list into the AT-SPI walker so top-level
	// frames can be correlated to their X11 window_id (task-11). The
	// a11y package itself can't import internal/window without a
	// layering cycle, so the orchestrator threads the snapshot
	// through. Gio/ImGui apps don't expose AT-SPI elements and so
	// stay uncorrelated — no false positives.
	tree, _ := a11y.TreeWithWindows(ctx, 8, wins)
	out := contract.ObserveResult{
		Screen:        info,
		Windows:       wins,
		FocusedWindow: focused,
		Cursor:        cursor,
		Accessibility: tree,
		Backends: map[string]string{
			"screen": "x11",
			"window": "EWMH",
			"input":  "XTest",
		},
	}
	if includeScreenshot {
		shot, err := screen.Capture(ctx, screen.CaptureRequest{MaxEdge: 1568})
		if err != nil {
			return out, err
		}
		out.Screenshot = &shot
	}
	return out, nil
}
