// Package yield implements an XInput2-driven "active user" watcher
// that lets MyComputer pause execution when the human is driving the
// desktop. The watcher subscribes to XInput2 raw events on the root
// window (RawMotion, RawButtonPress, RawKeyPress) and forwards every
// event NOT generated by MC's own XTest synthetic input down a channel
// for the pipeline to act on.
//
// Implementation note on the transport: jezek/xgb (our X11 binding)
// does not ship an xinput2 sub-package, and we deliberately avoid
// adding cgo. Instead the watcher spawns `xinput test-xi2 --root`
// — a tiny X.Org utility that prints raw events as text — and parses
// stdout. The format is stable and machine-friendly:
//
//	EVENT type 17 (RawMotion)
//	    device: 2 (4)
//	    time:   123456789
//	    detail: 0
//
// "device: <master> (<slave>)" carries both the master device id and
// the slave device the event originated from. MC's own XTest synthetic
// input always originates from the "Virtual core XTEST pointer" /
// "Virtual core XTEST keyboard" slave devices (id 4 and 5 on a normal
// X server); the watcher resolves those ids up front via the device
// list at the top of the same xinput stream and drops any raw event
// whose slave id matches. That filter — plus dropping any line that
// includes a "flags:" line containing "pointer-emulated" — is what
// keeps MC from yielding to its own actions.
//
// The watcher is designed to be safe even when the host cannot run
// xinput at all: Start returns an error, and the pipeline treats yield
// as unavailable (no yielding, no doctor "ready" claim).
package yield

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

// EventKind identifies the XInput2 raw event kind.
type EventKind string

const (
	EventRawMotion      EventKind = "RawMotion"
	EventRawButtonPress EventKind = "RawButtonPress"
	EventRawKeyPress    EventKind = "RawKeyPress"
)

// Event is the parsed, filtered raw XInput2 event the pipeline sees.
// Synthetic events (originating from MC's XTest slave devices) are
// filtered before reaching the channel and never appear here.
type Event struct {
	TS      time.Time `json:"ts"`
	Kind    EventKind `json:"event_type"`
	Master  int       `json:"device_id"`
	Slave   int       `json:"source_id"`
	Detail  int       `json:"detail,omitempty"`
	RawLine string    `json:"-"`
}

// XTestDevices is the set of XInput2 slave device ids whose events MC
// must treat as synthetic (its own XTest input) and drop. Resolved at
// watcher start from the xinput device list. Falls back to the well-
// known X server defaults (4=XTEST pointer, 5=XTEST keyboard) if the
// list cannot be parsed.
type XTestDevices struct {
	Pointer  int
	Keyboard int
}

// Default returns the well-known XTEST slave device ids most X
// servers assign. Used when the xinput device list cannot be parsed.
func Default() XTestDevices {
	return XTestDevices{Pointer: 4, Keyboard: 5}
}

// Watcher subscribes to XInput2 raw events from the X server and emits
// filtered Events for real (non-MC-synthetic) user input. The watcher
// uses an external `xinput test-xi2 --root` process as the event
// source — see package docs for rationale.
//
// A Watcher is single-shot: call Start once, read Events(), and either
// let the context cancel it or call Stop. Watchers are NOT goroutine-
// safe to start; only one Start may run concurrently per instance.
type Watcher struct {
	// Command is the xinput binary to invoke. Defaults to "xinput".
	// Exposed for tests that want to point at a fixture script.
	Command string
	// Args overrides the default argv. Defaults to ["test-xi2", "--root"].
	Args []string
	// Buffer sizes the events channel. Defaults to 64.
	Buffer int
	// XTest, when non-zero, pins the synthetic-device ids instead of
	// resolving them from xinput's device list. Tests use this to make
	// filtering deterministic without an X server.
	XTest XTestDevices

	mu      sync.Mutex
	started bool
	cmd     *exec.Cmd
	events  chan Event
	done    chan struct{}
	errOnce sync.Once
	lastErr error
}

// Events returns the channel raw user events are delivered on. The
// channel is closed when the watcher exits (context cancel, process
// exit, or Stop). Safe to call before Start; the channel is created
// lazily so consumers can register a select case ahead of time.
func (w *Watcher) Events() <-chan Event {
	w.mu.Lock()
	defer w.mu.Unlock()
	if w.events == nil {
		buf := w.Buffer
		if buf <= 0 {
			buf = 64
		}
		w.events = make(chan Event, buf)
	}
	return w.events
}

// Err returns the first non-nil error the watcher recorded. Returns
// nil while running cleanly; returns the process exit / pipe error
// after the watcher stops abnormally.
func (w *Watcher) Err() error {
	w.mu.Lock()
	defer w.mu.Unlock()
	return w.lastErr
}

// Start launches the xinput subprocess and begins reading raw events.
// Returns a Dependency error if xinput cannot be invoked. Once Start
// returns nil the caller MUST read from Events() to avoid back-
// pressure stalling the parser goroutine.
func (w *Watcher) Start(ctx context.Context) error {
	w.mu.Lock()
	if w.started {
		w.mu.Unlock()
		return errors.New("yield.Watcher: already started")
	}
	cmdName := w.Command
	if cmdName == "" {
		cmdName = "xinput"
	}
	args := w.Args
	if len(args) == 0 {
		args = []string{"test-xi2", "--root"}
	}
	if w.events == nil {
		buf := w.Buffer
		if buf <= 0 {
			buf = 64
		}
		w.events = make(chan Event, buf)
	}
	if w.done == nil {
		w.done = make(chan struct{})
	}

	cmd := exec.CommandContext(ctx, cmdName, args...)
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		w.mu.Unlock()
		return fmt.Errorf("yield: stdout pipe: %w", err)
	}
	// xinput writes its device list and event stream to stdout. We
	// also capture stderr to surface errors at Stop time. A nil
	// stderr is fine for tests.
	cmd.Stderr = io.Discard

	if err := cmd.Start(); err != nil {
		w.mu.Unlock()
		return fmt.Errorf("yield: start %s: %w", cmdName, err)
	}
	w.cmd = cmd
	w.started = true
	xtest := w.XTest
	w.mu.Unlock()

	go w.run(stdout, xtest)
	return nil
}

// Stop terminates the watcher process and closes the events channel.
// Idempotent.
func (w *Watcher) Stop() {
	w.mu.Lock()
	cmd := w.cmd
	w.mu.Unlock()
	if cmd != nil && cmd.Process != nil {
		_ = cmd.Process.Kill()
	}
	if w.done != nil {
		<-w.done
	}
}

func (w *Watcher) recordErr(err error) {
	if err == nil {
		return
	}
	w.errOnce.Do(func() {
		w.mu.Lock()
		w.lastErr = err
		w.mu.Unlock()
	})
}

func (w *Watcher) run(r io.Reader, pinned XTestDevices) {
	defer func() {
		w.mu.Lock()
		ev := w.events
		w.mu.Unlock()
		if ev != nil {
			close(ev)
		}
		if w.done != nil {
			close(w.done)
		}
	}()
	xtest := pinned
	if xtest == (XTestDevices{}) {
		xtest = Default()
	}
	emit := func(e Event) {
		w.mu.Lock()
		ev := w.events
		w.mu.Unlock()
		if ev == nil {
			return
		}
		select {
		case ev <- e:
		default:
			// Back-pressure: pipeline isn't draining fast enough.
			// Drop on the floor — yield's design tolerates dropped
			// raw events because the watcher fires constantly while
			// the user is active. We never want a slow consumer to
			// block the parser goroutine.
		}
	}
	parser := newParser(xtest)
	scanner := bufio.NewScanner(r)
	// xinput lines are short; the default 64K buffer is plenty, but
	// be defensive against very long device-name lines on machines
	// with many input devices.
	scanner.Buffer(make([]byte, 0, 16*1024), 256*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if ev, ok := parser.feed(line); ok {
			emit(ev)
		}
	}
	// Flush the last partial event the parser is holding so the final
	// raw event in the stream actually reaches the consumer.
	if ev, ok := parser.flush(); ok {
		emit(ev)
	}
	if err := scanner.Err(); err != nil {
		w.recordErr(err)
	}
	if w.cmd != nil {
		_ = w.cmd.Wait()
	}
}

// parser is a tiny state machine over xinput's textual raw-event
// output. It collects one event's worth of lines, then synthesizes
// an Event when the next blank line or next "EVENT type" header
// arrives. Synthetic events (slave device id == one of the XTest
// devices, or any line containing "pointer-emulated") are
// suppressed.
type parser struct {
	xtest   XTestDevices
	current *partial
}

type partial struct {
	kind     EventKind
	master   int
	slave    int
	detail   int
	flagsSyn bool
	rawLines []string
}

var (
	eventHeaderRE = regexp.MustCompile(`^EVENT type \d+ \((Raw[A-Za-z]+)\)$`)
	deviceRE      = regexp.MustCompile(`^\s*device:\s+(\d+)(?:\s+\((\d+)\))?`)
	detailRE      = regexp.MustCompile(`^\s*detail:\s+(\d+)`)
	flagsRE       = regexp.MustCompile(`^\s*flags:\s+(.*)$`)
	deviceListRE  = regexp.MustCompile(`(?i)Virtual core XTEST (pointer|keyboard).*?\bid=(\d+)`)
)

func newParser(xtest XTestDevices) *parser {
	return &parser{xtest: xtest}
}

// feed consumes one line of xinput output and, when an event has
// been fully accumulated, returns it. Returns ok=false when the
// line is not the last line of an event, or when the accumulated
// event is synthetic and must be dropped.
func (p *parser) feed(line string) (Event, bool) {
	// Top-of-stream device list: harvest XTEST slave ids so the
	// filter is correct even on X servers that don't use the
	// stock 4/5 assignment.
	if m := deviceListRE.FindStringSubmatch(line); m != nil {
		if id, err := strconv.Atoi(m[2]); err == nil {
			switch strings.ToLower(m[1]) {
			case "pointer":
				p.xtest.Pointer = id
			case "keyboard":
				p.xtest.Keyboard = id
			}
		}
		return Event{}, false
	}

	if m := eventHeaderRE.FindStringSubmatch(strings.TrimSpace(line)); m != nil {
		out, ok := p.flush()
		p.current = &partial{kind: EventKind(m[1])}
		if ok {
			return out, true
		}
		return Event{}, false
	}

	if p.current == nil {
		return Event{}, false
	}
	p.current.rawLines = append(p.current.rawLines, line)

	if m := deviceRE.FindStringSubmatch(line); m != nil {
		if v, err := strconv.Atoi(m[1]); err == nil {
			p.current.master = v
		}
		if m[2] != "" {
			if v, err := strconv.Atoi(m[2]); err == nil {
				p.current.slave = v
			}
		}
	}
	if m := detailRE.FindStringSubmatch(line); m != nil {
		if v, err := strconv.Atoi(m[1]); err == nil {
			p.current.detail = v
		}
	}
	if m := flagsRE.FindStringSubmatch(line); m != nil {
		if strings.Contains(strings.ToLower(m[1]), "pointer-emulated") ||
			strings.Contains(strings.ToLower(m[1]), "pointeremulated") ||
			strings.Contains(strings.ToLower(m[1]), "emulated") {
			p.current.flagsSyn = true
		}
	}
	return Event{}, false
}

// flush finalizes the current partial event, applies the synthetic
// filter, and returns the Event if it should be delivered. Called
// when a new event header arrives (or the parser is closed).
func (p *parser) flush() (Event, bool) {
	cur := p.current
	p.current = nil
	if cur == nil {
		return Event{}, false
	}
	if !isRawEvent(cur.kind) {
		return Event{}, false
	}
	// Synthetic filter: dual-channel.
	//   1. XIPointerEmulated flag (text "pointer-emulated").
	//   2. Slave device id matches one of MC's XTest devices.
	if cur.flagsSyn {
		return Event{}, false
	}
	if p.xtest.Pointer != 0 && cur.slave == p.xtest.Pointer {
		return Event{}, false
	}
	if p.xtest.Keyboard != 0 && cur.slave == p.xtest.Keyboard {
		return Event{}, false
	}
	return Event{
		TS:      time.Now().UTC(),
		Kind:    cur.kind,
		Master:  cur.master,
		Slave:   cur.slave,
		Detail:  cur.detail,
		RawLine: strings.Join(cur.rawLines, "\n"),
	}, true
}

func isRawEvent(kind EventKind) bool {
	switch kind {
	case EventRawMotion, EventRawButtonPress, EventRawKeyPress:
		return true
	}
	return false
}

// Available reports whether the host has the xinput binary available
// for use as the yield event source. Used by doctor and by the
// pipeline to decide whether to instantiate a watcher.
func Available() (bool, string) {
	path, err := exec.LookPath("xinput")
	if err != nil {
		return false, ""
	}
	return true, path
}

// SampleUserEvents starts a watcher for the given duration and counts
// how many user (non-synthetic) raw events arrive. Used by doctor's
// xinput2 row to report whether the listener actually sees events.
// Returns (count, error). A zero count with nil error means the
// listener is healthy but the user was idle during the sample.
func SampleUserEvents(ctx context.Context, d time.Duration) (int, error) {
	if d <= 0 {
		d = 200 * time.Millisecond
	}
	ok, _ := Available()
	if !ok {
		return 0, errors.New("xinput binary not found in PATH")
	}
	sctx, cancel := context.WithTimeout(ctx, d)
	defer cancel()
	w := &Watcher{}
	if err := w.Start(sctx); err != nil {
		return 0, err
	}
	count := 0
	for {
		select {
		case _, ok := <-w.Events():
			if !ok {
				return count, nil
			}
			count++
		case <-sctx.Done():
			w.Stop()
			// Drain whatever's left.
			for range w.Events() {
				count++
			}
			return count, nil
		}
	}
}
